import { library } from '@fortawesome/fontawesome-svg-core';

import {
    faHome,
    faAddressCard,
    faEnvelope,
    faFolderOpen,
    faAngleDown,
    faAngleUp,
    faBars,
    faServer,
    faMobileAlt,
    faDesktop,
    faWrench,
    faDatabase,
    faAngleRight,
    faCode,
    faBug,
    faBriefcase,
    faGraduationCap,
    faKeyboard,
    faCertificate,
    faBook,
    faUser,
    faExclamationCircle,
    faFilePdf,
} from '@fortawesome/free-solid-svg-icons';
import { faLinkedin, faGithub } from '@fortawesome/free-brands-svg-icons';

library.add(
    faHome,
    faAddressCard,
    faEnvelope,
    faFolderOpen,
    faLinkedin,
    faGithub,
    faAngleDown,
    faAngleUp,
    faBars,
    faServer,
    faMobileAlt,
    faDesktop,
    faWrench,
    faDatabase,
    faAngleRight,
    faCode,
    faBug,
    faBriefcase,
    faGraduationCap,
    faKeyboard,
    faCertificate,
    faBook,
    faUser,
    faExclamationCircle,
    faFilePdf,
);
